<a href="https://colab.research.google.com/github/harshsrivastava096/Python-Tutorial/blob/main/Python_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# NUMPY

In [63]:
# Type knowing
l=[1,2,3,4,5]
type(l)
l

[1, 2, 3, 4, 5]

In [ ]:
#Creation of array
arr= np.array([1,2,3,4,5])
arr

In [ ]:
#element-wise operation
arr+2

In [57]:
# Addition of Array
a = 10
b = 20
c = a+b
c

30

In [58]:
# Substraction of Array
a = 10
b = 20
c = b-a
c

10

In [59]:
# Multiplication of Array
a = 10
b = 20
c = a*b
c

200

In [60]:
# division of Array
a = 10
b = 20
c = b/a
c

2.0

In [8]:
arr=np.array([True])
arr=np.array([False])
arr=np.array([True,1])
arr=np.array([True,1,2.5])
arr=np.array([True,1,2.5,6+5j])
arr=np.array([True,1,2.5,6+5j,"numpy"])
arr=np.array([True,1,2.5,6+5j,"numpy",{1,2}])
arr=np.array([True,1,2.5,6+5j,"numpy",{1,2},{1:"a",2:"b"}])

print(arr)
print(arr.dtype)

[False]
bool


In [16]:
#[20,40,60,80,30,50]
arr1=np.array([20,40,60,80,30,50])
arr1

array([20, 40, 60, 80, 30, 50])

In [13]:
# [10,20,35.6,80]
ar2=np.array([10,20,35.6,80])
print(ar2)
ar2.dtype


dtype('float64')

In [28]:
# {10,"numpy",30,"Hi"}
ar3=np.array({10,"numpy",30,"Hi"})
print(ar3)
ar3.dtype

{'numpy', 10, 'Hi', 30}


dtype('O')

In [31]:
# ["bye",6+8j,{"d":12,"e":45},67.9]
l=["bye",6+8j,{"d":12,"e":45},67.9]
ar4=np.array(l)
print(ar4)
ar4.dtype

['bye' (6+8j) {'d': 12, 'e': 45} 67.9]


dtype('O')

In [50]:
#Typecasting using astype() part1
ar5=np.array([1,2,3])
b5= ar5.astype(bool)
print(b5)
b5.dtype

[ True  True  True]


dtype('bool')

In [56]:
#typecasting using astype() part2

arr=np.array(["1","2","67.78","65"])
bl=arr.astype(float)
print(bl)
bl.dtype

[ 1.    2.   67.78 65.  ]


dtype('float64')

In [53]:
# Want Output as [False,Str,Object]
ar6 = np.array([False, "Str", object])
print(ar6)


[False 'Str' <class 'object'>]


In [65]:
# Checking Dimension
ar7= np.array([1,2,3,4])
print(ar7)
arr.ndim

[1 2 3 4]


1

In [66]:
# Two Dimension Array
ar8=np.array([[1,2,5],[3,4,6]])
print(ar8)
ar8.ndim

[[1 2 5]
 [3 4 6]]


2